# Pull gems from RubyGems
source "https://rubygems.org"

# gem "rails"

# Sass, Compass and extensions.
# '~>' Refers to all versions of the given gem on the current full version number. For a specific version of a gem, remove the '~>' or use greater than '>','>='
gem "sass", '~> 3.3'                 # Sass version with source-maps https://github.com/Compass/compass/issues/1108
gem 'compass', '~>1.0.0.alpha.19'    # Framework built on Sass.
gem 'compass-rgbapng'                # Turns rgba() into .png's for backwards compatibility.
gem 'singularitygs'                  # Alternative to the Susy grid framework.
gem 'breakpoint'                     # Manages CSS media queries.
gem 'oily_png'                       # Faster Compass sprite generation.
gem 'compass-css-arrow'              # Easy css3 arrows
#gem 'sassy-buttons'                 # Easy css3 buttons
#gem 'susy'                          # Susy grid framework.
#gem 'toolkit'                       # Compass utility from the fabulous Snugug.
#gem 'css_parser'                    # Helps `compass stats` output statistics.

# General Bundler commands
# Run 'bundle install' to create Gemfile.lock and download gems to your local machine.
# OR Run 'bundle install --path .bundle' to place the needed gems right inside your project. To achieve this run bundle install with the path option.
# Run 'bundle check' to check dependencies without installing new gems.
# Run `bundle exec compass watch` instead of simply `compass watch` to compile and live reload with project specific gems.
# Run 'bundle exec compass compile --sourcemap' to compile project gems with sourcemaps
# Run 'bundle exec compass watch --sourcemap' to continuously compile project gems with sourcemaps

